groups:
  - name: customerai_metrics
    rules:
      - record: job:http_requests_total:rate5m
        expr: sum(rate(http_requests_total[5m])) by (job)
      
      - record: job:http_request_duration_seconds:p95
        expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (job, le))
      
      - record: job:errors:rate5m
        expr: sum(rate(http_requests_total{status_code=~"5.."}[5m])) by (job)
      
      - record: job:memory_usage:bytes
        expr: sum(process_resident_memory_bytes) by (job)