name: Update Project Status

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [closed]
    branches:
      - main
      - master

jobs:
  update-status:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for git log analysis

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        # Install pinned version of argon2-cffi-bindings first
        pip install argon2-cffi-bindings==21.2.0
        # Install core dependencies
        pip install pytest pytest-cov flake8
        # Install project dependencies with constraints
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt --no-deps
          pip install -r requirements.txt
        fi

    - name: Update project status
      run: |
        python scripts/update_project_status.py

    - name: Check for changes
      id: check_changes
      run: |
        git diff --exit-code PROJECT_STATUS.md || echo "status_changed=true" >> $GITHUB_OUTPUT

    - name: Commit and push if changed
      if: steps.check_changes.outputs.status_changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add PROJECT_STATUS.md
        git commit -m "Auto-update project status [skip ci]"
        git push
