name: Update Project Status

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [closed]
    branches:
      - main
      - master

jobs:
  update-status:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for git log analysis

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      shell: bash
      run: |
        # Upgrade pip and core tools
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel

        # Clear pip cache
        python -m pip cache purge

        # Install core dependencies with pinned versions
        pip install --no-cache-dir pytest==8.0.0
        pip install --no-cache-dir pytest-cov==4.1.0
        pip install --no-cache-dir flake8==7.0.0

        # Install pinned version of critical dependencies
        pip install --no-cache-dir argon2-cffi-bindings==21.2.0
        pip install --no-cache-dir argon2-cffi==21.3.0

        # Install project dependencies
        if [ -f "requirements.txt" ]; then
          pip install --no-cache-dir -r requirements.txt
        fi

    - name: Update project status
      run: |
        python scripts/update_project_status.py

    - name: Check for changes
      id: check_changes
      run: |
        git diff --exit-code PROJECT_STATUS.md || echo "status_changed=true" >> $GITHUB_OUTPUT

    - name: Commit and push if changed
      if: steps.check_changes.outputs.status_changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add PROJECT_STATUS.md
        git commit -m "Auto-update project status [skip ci]"
        git push
